# deps
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

# build
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_GRAFANA_BASE
ARG NEXT_PUBLIC_GRAFANA_DASHBOARD_UID
ARG NEXT_PUBLIC_GRAFANA_DASHBOARD_SLUG
ARG NEXT_PUBLIC_GRAFANA_ORG_ID
ARG NEXT_PUBLIC_GRAFANA_DATASOURCE
ARG NEXT_PUBLIC_GRAFANA_CLUSTER
ARG NEXT_PUBLIC_GRAFANA_FROM
ARG NEXT_PUBLIC_GRAFANA_TO
ARG NEXT_PUBLIC_GRAFANA_TIMEZONE
ARG NEXT_PUBLIC_GRAFANA_REFRESH
ARG NEXT_PUBLIC_GRAFANA_FEATURE_DASHBOARD_SCENE

ENV NEXT_PUBLIC_GRAFANA_BASE=$NEXT_PUBLIC_GRAFANA_BASE
ENV NEXT_PUBLIC_GRAFANA_DASHBOARD_UID=$NEXT_PUBLIC_GRAFANA_DASHBOARD_UID
ENV NEXT_PUBLIC_GRAFANA_DASHBOARD_SLUG=$NEXT_PUBLIC_GRAFANA_DASHBOARD_SLUG
ENV NEXT_PUBLIC_GRAFANA_ORG_ID=$NEXT_PUBLIC_GRAFANA_ORG_ID
ENV NEXT_PUBLIC_GRAFANA_DATASOURCE=$NEXT_PUBLIC_GRAFANA_DATASOURCE
ENV NEXT_PUBLIC_GRAFANA_CLUSTER=$NEXT_PUBLIC_GRAFANA_CLUSTER
ENV NEXT_PUBLIC_GRAFANA_FROM=$NEXT_PUBLIC_GRAFANA_FROM
ENV NEXT_PUBLIC_GRAFANA_TO=$NEXT_PUBLIC_GRAFANA_TO
ENV NEXT_PUBLIC_GRAFANA_TIMEZONE=$NEXT_PUBLIC_GRAFANA_TIMEZONE
ENV NEXT_PUBLIC_GRAFANA_REFRESH=$NEXT_PUBLIC_GRAFANA_REFRESH
ENV NEXT_PUBLIC_GRAFANA_FEATURE_DASHBOARD_SCENE=$NEXT_PUBLIC_GRAFANA_FEATURE_DASHBOARD_SCENE
ARG NEXT_PUBLIC_NODE_1_IP
ARG NEXT_PUBLIC_NODE_2_IP
ARG NEXT_PUBLIC_NODE_3_IP
ARG NEXT_PUBLIC_NODE_4_IP
ARG NEXT_PUBLIC_NODE_5_IP
ARG NEXT_PUBLIC_NODE_6_IP

ENV NEXT_PUBLIC_NODE_1_IP=$NEXT_PUBLIC_NODE_1_IP
ENV NEXT_PUBLIC_NODE_2_IP=$NEXT_PUBLIC_NODE_2_IP
ENV NEXT_PUBLIC_NODE_3_IP=$NEXT_PUBLIC_NODE_3_IP
ENV NEXT_PUBLIC_NODE_4_IP=$NEXT_PUBLIC_NODE_4_IP
ENV NEXT_PUBLIC_NODE_5_IP=$NEXT_PUBLIC_NODE_5_IP
ENV NEXT_PUBLIC_NODE_6_IP=$NEXT_PUBLIC_NODE_6_IP
RUN npm run build

# runtime
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3000

CMD ["npm", "run", "start"]